# This is a config for E2B sandbox template.
# You can use template ID (c7su7oxpt6vttzklc6au) or template name (vibe-nextjs-kc-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-kc-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-kc-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-kc-test-2')

team_id = "d930a00b-2dcc-43e2-98f6-f413c70f8948"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-kc-test-2"
template_id = "c7su7oxpt6vttzklc6au"
